
//#include <stdlib.h>
//#include <stdio.h>
//#include <math.h>
//#include <string.h>
#include <stdint.h>
#include "Microphone.h"

//#define TEST_LENGTH_SAMPLES 4096
#define TEST_LENGTH_SAMPLES 2048
////#define TEST_LENGTH_SAMPLES 1400
//#define SPEECH_TEST_LENGTH_SAMPLES 4096
#define SPEECH_TEST_LENGTH_SAMPLES 512
#define MAX_ITERATIONS 8


#define ADDR_FFT_BIN_INPUT_XCORR_R            ADDR_SPEECH_FFT_MODEL_B3 + 32 * 1024
#define ADDR_FFT_BIN_INPUT_XCORR_G            ADDR_FFT_BIN_INPUT_XCORR_R + 32 * 1024
#define ADDR_FFT_BIN_INPUT_XCORR_B            ADDR_FFT_BIN_INPUT_XCORR_G + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_XCORR_R           ADDR_FFT_BIN_INPUT_XCORR_B + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_XCORR_G           ADDR_FFT_BIN_OUTPUT_XCORR_R + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_XCORR_B           ADDR_FFT_BIN_OUTPUT_XCORR_G + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R0   ADDR_FFT_BIN_OUTPUT_XCORR_B + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R1   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R0 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R2   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R1 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R3   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R2 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R4   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R3 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R5   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R4 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R6   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R5 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R7   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R6 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G0   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_R7 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G1   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G0 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G2   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G1 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G3   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G2 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G4   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G3 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G5   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G4 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G6   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G5 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G7   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G6 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B0   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_G7 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B1   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B0 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B2   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B1 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B3   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B2 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B4   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B3 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B5   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B4 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B6   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B5 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B7   ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B6 + 32 * 1024
#define ADDR_FFT_BIN_OUTPUT_SPEECH_TEST       ADDR_FFT_BIN_OUTPUT_SPEECH_MODEL_B7 + 32 * 1024

int32_t fft_test(void);

typedef struct RGB_data_t{
    float32_t max[MAX_ITERATIONS];
    float32_t total;
} RGB_data_t;

typedef struct RGB_results_t{
    RGB_data_t red;
    RGB_data_t green;
    RGB_data_t blue;
} RGB_results_t;

void fft_speech_test(int iteration);
void fft_speech_models(void);
void fft_compare_models_test(void);
void speech_cross_correlation_test(int iteration);

extern void delay(uint32_t i);